/** Defines scan suffixes, entrypoint names, and ignored filesystem paths. */
export const ENTRYPOINT_BASENAMES = new Set([
  "__main__.py",
  "main.py",
  "app.py",
  "cli.py",
  "server.py",
  "main.js",
  "main.ts",
  "main.jsx",
  "main.tsx",
  "main.mjs",
  "main.cjs",
  "main.mts",
  "main.cts",
  "app.js",
  "app.ts",
  "app.jsx",
  "app.tsx",
  "app.mjs",
  "app.cjs",
  "app.mts",
  "app.cts",
  "index.js",
  "index.ts",
  "index.jsx",
  "index.tsx",
  "index.mjs",
  "index.cjs",
  "index.mts",
  "index.cts",
]);

export const TYPESCRIPT_SUFFIXES = new Set([
  ".ts",
  ".tsx",
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
  ".mts",
  ".cts",
]);
export const PY_SUFFIXES = new Set([".py"]);

export const TEXT_SUFFIXES = new Set([
  ".c",
  ".cc",
  ".conf",
  ".cpp",
  ".css",
  ".eex",
  ".erl",
  ".ex",
  ".exs",
  ".go",
  ".graphql",
  ".h",
  ".heex",
  ".hpp",
  ".hrl",
  ".html",
  ".java",
  ".json",
  ".jsonc",
  ".livemd",
  ".md",
  ".mmd",
  ".prisma",
  ".proto",
  ".rs",
  ".rules",
  ".sh",
  ".sql",
  ".toml",
  ".txt",
  ".yaml",
  ".yml",
]);

export const SCAN_SUFFIXES = new Set([...PY_SUFFIXES, ...TYPESCRIPT_SUFFIXES, ...TEXT_SUFFIXES]);

export const SCAN_BASENAMES = new Set([
  ".env",
  ".gitignore",
  "Dockerfile",
  "Justfile",
  "Makefile",
  "Procfile",
]);

export const IGNORED_FILE_SUFFIXES = new Set([
  ".7z",
  ".app",
  ".bak",
  ".beam",
  ".bin",
  ".csv",
  ".db",
  ".db-shm",
  ".db-wal",
  ".doc",
  ".docx",
  ".DS_Store",
  ".exe",
  ".gif",
  ".ico",
  ".ipynb",
  ".jpeg",
  ".jpg",
  ".local",
  ".lock",
  ".log",
  ".map",
  ".mp4",
  ".msg",
  ".parquet",
  ".pdf",
  ".png",
  ".pyc",
  ".sqlite",
  ".svg",
  ".tsbuildinfo",
  ".webp",
  ".xls",
  ".xlsm",
  ".xlsx",
  ".zip",
]);

export const IGNORED_DIR_NAMES = new Set([
  ".cache",
  ".context-graph",
  ".git",
  ".mypy_cache",
  ".next",
  ".pytest_cache",
  ".ruff_cache",
  ".turbo",
  ".understand-anything",
  ".venv",
  "__pycache__",
  "_build",
  "_generated",
  "_next",
  "backup",
  "build",
  "coverage",
  "deps",
  "dist",
  "out",
  "node_modules",
  "public",
  "references",
  "user-data",
  "venv",
  "vendor",
]);

export const ROOT_IGNORED_DIR_NAMES = new Set(["target"]);

export const KEPT_HIDDEN_DIR_NAMES = new Set([".github"]);

export const TYPESCRIPT_LANG_BY_SUFFIX: Record<string, string> = {
  ".cjs": "javascript",
  ".cts": "typescript",
  ".js": "javascript",
  ".jsx": "jsx",
  ".mjs": "javascript",
  ".mts": "typescript",
  ".ts": "typescript",
  ".tsx": "tsx",
};
